# <span style="color:darkblue"> QTM 151 - Assignment 8 </span>

## Try to submit as an HTML file



### Print your name below

In [1]:
# Write your answer here

print("Joanna Yao")

Joanna Yao

### Import the "pandas" library

In [2]:
# Write your answer here

import pandas as pd

### You will need the material from Lecture 14 and 15 for this assignment.



### Import the dataset "imdb_top_1000.csv" and save it as "movies." <br> 
This includes data on the top 1000 movies by IMDB rating.

In [6]:
# Write your answer here

movies=pd.read_csv("data_raw/imdb_top_1000.csv")
movies

,Name,Released_Year,Length,Genre,IMDB_Rating,Overview,Director,Star1,Star2,Gross
0,The Shawshank Redemption,1994,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,Frank Darabont,Tim Robbins,Morgan Freeman,"28,341,469"
1,The Godfather,1972,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,Francis Ford Coppola,Marlon Brando,Al Pacino,"134,966,411"
2,The Dark Knight,2008,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,Christopher Nolan,Christian Bale,Heath Ledger,"534,858,444"
3,The Godfather: Part II,1974,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,Francis Ford Coppola,Al Pacino,Robert De Niro,"57,300,000"
4,12 Angry Men,1957,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,Sidney Lumet,Henry Fonda,Lee J. Cobb,"4,360,000"
...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,115 min,"Comedy, Drama, Romance",7.6,A young New York socialite becomes interested ...,Blake Edwards,Audrey Hepburn,George Peppard,NaN
996,Giant,1956,201 min,"Drama, Western",7.6,Sprawling epic covering the life of a Texas ca...,George Stevens,Elizabeth Taylor,Rock Hudson,NaN
997,From Here to Eternity,1953,118 min,"Drama, Romance, War",7.6,"In Hawaii in 1941, a private is cruelly punish...",Fred Zinnemann,Burt Lancaster,Montgomery Clift,"30,500,000"
998,Lifeboat,1944,97 min,"Drama, War",7.6,Several survivors of a torpedoed merchant ship...,Alfred Hitchcock,Tallulah Bankhead,John Hodiak,NaN
999,The 39 Steps,1935,86 min,"Crime, Mystery, Thriller",7.6,A man in London tries to help a counter-espion...,Alfred Hitchcock,Robert Donat,Madeleine Carroll,NaN

### (a) Groupby + Aggregate Statistics

Create a new dataset **"movies_agg"** by grouping the "movies" dataset by **"Genre"** and then computing <br>the following aggregate statistics for **"IMDB_Rating"**:

- **Mean**
- **Standard Deviation**
- **Minimum**
- **Maximum**

Add a chain to sort by the mean IMDB rating in descending order.

Display the resulting dataset **"movies_agg"**.

In [10]:
# Write your own code

movies_agg=(movies.groupby("Genre")
            .agg(mean_rating=('IMDB_Rating','mean'),
                 sd_rating=('IMDB_Rating','std'),
                 min_rating=('IMDB_Rating','min'),
                 max_rating=('IMDB_Rating','max'))
                 .sort_values("mean_rating",ascending=False))

movies_agg

                            mean_rating  sd_rating  min_rating  max_rating
Genre
Animation, Drama, War              8.50        NaN         8.5         8.5
Drama, Musical                     8.40        NaN         8.4         8.4
Action, Sci-Fi                     8.40   0.360555         8.0         8.7
Drama, Mystery, War                8.35   0.070711         8.3         8.4
Western                            8.35   0.420317         7.8         8.8
...                                 ...        ...         ...         ...
Adventure, Comedy, War             7.60        NaN         7.6         7.6
Animation, Comedy, Crime           7.60        NaN         7.6         7.6
Action, Adventure, Family          7.60        NaN         7.6         7.6
Animation, Drama, Romance          7.60        NaN         7.6         7.6
Action, Adventure, Mystery         7.60        NaN         7.6         7.6

[202 rows x 4 columns]

### (b) Merge Data

Create a new dataset **"movies_merge"** by merging the aggregate information <br> 
from (a) into "movies".

Display the resulting dataset **"movies_merge"**.

In [14]:
# Write your own code

movies_merge=pd.merge(movies,movies_agg,on="Genre",how="left")
movies_merge

,Name,Released_Year,Length,Genre,IMDB_Rating,Overview,Director,Star1,Star2,Gross,mean_rating,sd_rating,min_rating,max_rating
0,The Shawshank Redemption,1994,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,Frank Darabont,Tim Robbins,Morgan Freeman,"28,341,469",7.975294,0.305468,7.6,9.3
1,The Godfather,1972,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,Francis Ford Coppola,Marlon Brando,Al Pacino,"134,966,411",8.157692,0.448262,7.6,9.2
2,The Dark Knight,2008,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,Christopher Nolan,Christian Bale,Heath Ledger,"534,858,444",7.880000,0.316664,7.6,9.0
3,The Godfather: Part II,1974,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,Francis Ford Coppola,Al Pacino,Robert De Niro,"57,300,000",8.157692,0.448262,7.6,9.2
4,12 Angry Men,1957,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,Sidney Lumet,Henry Fonda,Lee J. Cobb,"4,360,000",8.157692,0.448262,7.6,9.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,115 min,"Comedy, Drama, Romance",7.6,A young New York socialite becomes interested ...,Blake Edwards,Audrey Hepburn,George Peppard,NaN,7.877419,0.257824,7.6,8.6
996,Giant,1956,201 min,"Drama, Western",7.6,Sprawling epic covering the life of a Texas ca...,George Stevens,Elizabeth Taylor,Rock Hudson,NaN,7.980000,0.363318,7.6,8.4
997,From Here to Eternity,1953,118 min,"Drama, Romance, War",7.6,"In Hawaii in 1941, a private is cruelly punish...",Fred Zinnemann,Burt Lancaster,Montgomery Clift,"30,500,000",8.025000,0.368556,7.6,8.5
998,Lifeboat,1944,97 min,"Drama, War",7.6,Several survivors of a torpedoed merchant ship...,Alfred Hitchcock,Tallulah Bankhead,John Hodiak,NaN,8.073333,0.276371,7.6,8.6
999,The 39 Steps,1935,86 min,"Crime, Mystery, Thriller",7.6,A man in London tries to help a counter-espion...,Alfred Hitchcock,Robert Donat,Madeleine Carroll,NaN,8.133333,0.472582,7.6,8.5

### (c) Rename Columns + Dictionaries

Create a new dataset **"movies_rename"** by renaming the following columns in <br>the "movies" dataset using a dictionary:

- "Name" --> **"Movie_Title"**
- "Length" --> **"Runtime"**
- "Gross" --> **"Revenue"**

Verify that this renaming worked by printing the lists of the old ("movies") and new <br>("movies_rename") column names.

In [33]:
# Write your own code
movies_rename=movies.rename(columns={'Name' : 'Movie_Title', 'Length' : 'Runtime', 'Gross' : 'Revenue'}) # column names match directly

# verify
print(movies.columns.values)
print(movies_rename.columns.values)

['Name' 'Released_Year' 'Length' 'Genre' 'IMDB_Rating' 'Overview'
 'Director' 'Star1' 'Star2' 'Gross']
['Movie_Title' 'Released_Year' 'Runtime' 'Genre' 'IMDB_Rating' 'Overview'
 'Director' 'Star1' 'Star2' 'Revenue']

### (d) Split Data

Use ".query()" to split the "movies_rename" dataset from (c) into different parts:

- Those directed by **Steven Spielberg**, saved to a dataset titled **"movies_spielberg"**
- Those directed by **Christopher Nolan**, saved to a dataset titled **"movies_nolan"**

In [38]:
# Write your own code
movies_spielberg=(movies_rename.query("Director == 'Steven Spielberg'"))
movies_spielberg

movies_nolan=(movies_rename.query("Director == 'Christopher Nolan'"))
movies_nolan

,Movie_Title,Released_Year,Runtime,Genre,IMDB_Rating,Overview,Director,Star1,Star2,Revenue
2,The Dark Knight,2008,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,Christopher Nolan,Christian Bale,Heath Ledger,"534,858,444"
8,Inception,2010,148 min,"Action, Adventure, Sci-Fi",8.8,A thief who steals corporate secrets through t...,Christopher Nolan,Leonardo DiCaprio,Joseph Gordon-Levitt,"292,576,195"
21,Interstellar,2014,169 min,"Adventure, Drama, Sci-Fi",8.6,A team of explorers travel through a wormhole ...,Christopher Nolan,Matthew McConaughey,Anne Hathaway,"188,020,017"
36,The Prestige,2006,130 min,"Drama, Mystery, Sci-Fi",8.5,"After a tragic accident, two stage magicians e...",Christopher Nolan,Christian Bale,Hugh Jackman,"53,089,891"
63,The Dark Knight Rises,2012,164 min,"Action, Adventure",8.4,Eight years after the Joker's reign of anarchy...,Christopher Nolan,Christian Bale,Tom Hardy,"448,139,099"
69,Memento,2000,113 min,"Mystery, Thriller",8.4,A man with short-term memory loss attempts to ...,Christopher Nolan,Guy Pearce,Carrie-Anne Moss,"25,544,867"
155,Batman Begins,2005,140 min,"Action, Adventure",8.2,"After training with his mentor, Batman begins ...",Christopher Nolan,Christian Bale,Michael Caine,"206,852,432"
573,Dunkirk,2017,106 min,"Action, Drama, History",7.8,"Allied soldiers from Belgium, the British Empi...",Christopher Nolan,Fionn Whitehead,Barry Keoghan,"188,373,161"

### (e) Concatenate Data

Concatenate the datasets you created in (d) to a new dataset titled **"movies_concat"**.

Display the resulting dataset **"movies_concat"**.

In [8]:
# Write your own code