# <span style="color:darkblue"> QTM 151 - Quiz 3 </span>

## Try to submit as an HTML file

<font size="5"> 

Print your name below

In [1]:
# Write your answer here
print("Joanna Yao")

Joanna Yao

<font size = "5" >
This quiz is open book 

- You can use the lecture notes
- You will get partial credit for attempting the questions
- To get full credit, the code should run as intended
- You should <span style="color:red"> NOT </span> communicate with other students

Print the following message: <br>

"I will abide by Emory's code of conduct"

In [51]:
# Write your answer here:
print("I will abide by Emory's code of conduct")

I will abide by Emory's code of conduct

<font size = "5">

Import the libraries "numpy" and "pandas"

In [52]:
# Write your answer here
import pandas as pd
import numpy as np


<font size = "5">

(a) Replace the values of a column

<font size = "3">

- Import the "data_raw/constructors.csv" file
- Replace the values "British", "Japanese", and "Irish" with <br>
"UK", "Japan", "Ireland" in the column "nationality"


HINT: See the example in Lecture 12

In [6]:
# Write your own code

constructors=pd.read_csv("data_raw/constructors.csv")

# replacement
list_old=['British','Japanese','Irish']
list_new=['UK','Japan','Ireland']
constructors['nationality']=constructors['nationality'].replace(list_old,list_new)

constructors['nationality'] # confirm code works

0            UK
1        German
2            UK
3        French
4       Italian
         ...
206          UK
207    American
208          UK
209     Italian
210      French
Name: nationality, Length: 211, dtype: object

<font size = "5">

(b) Aggregate and query

<font size = "3">

- Import the "data_raw/sprint_results.csv" file
- Subset the observations for 'constructorId == 3' using ```.query()```
- Obtain the maximum of "laps" by "driverId" <br> 
 using ``` .groupby().agg() ```
- Subset the drivers with a maximum of laps $\ge 10$
- Store the results of all these operations in a dataframe <br>
```sprint_results_agg ```

In [53]:
# Write your own code
sprint_results=pd.read_csv("data_raw/sprint_results.csv")

# aggregate
sprint_results.query("(constructorId==3)")
driveragg=(sprint_results.groupby('driverId').agg(
    maximum_laps=('laps','max')))
driveragg

# subset
sprint_results_agg=driveragg.query("(maximum_laps>=10)")
sprint_results_agg

          maximum_laps
driverId
1                   24
4                   24
8                   24
9                   18
20                  24
815                 24
817                 24
822                 24
825                 24
830                 24
832                 24
839                 24
840                 24
841                 24
842                 24
844                 24
846                 24
847                 24
848                 23
849                 24
852                 24
853                 24
854                 24
855                 24

<font size = "5">

(c) Recode a numeric colum

<font size = "3">

- Import the "data_raw/races.csv" file
- Recode the "year" column into a new column "year_brackets" <br>
with the following categories

$\qquad$ ``` ["1950-1965","1966-1980","1980-onwards"] ```

$\qquad$ HINT: Use the "pd.cut()" command.

In [48]:
# Write your own code
races=pd.read_csv("data_raw/races.csv")
races['year']=pd.to_numeric(races['year'],errors='coerce') # ensure the year is numeric. 

# create bins & labels. 
bins_j=[1950,1965,1980,float('inf')]
labels_j=["1950-1965","1966-1980","1981-onward"]

# make categories. 
races['year_brackets']=pd.cut(races['year'],bins=bins_j,right=True,labels=labels_j)
races

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time,year_brackets
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,1981-onward
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,1981-onward
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,1981-onward
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,1981-onward
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,1981-onward
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1097,1116,2023,19,69,United States Grand Prix,2023-10-22,19:00:00,https://en.wikipedia.org/wiki/2023_United_Stat...,2023-10-20,17:30:00,2023-10-21,18:00:00,\N,\N,2023-10-20,21:00:00,2023-10-21,22:00:00,1981-onward
1098,1117,2023,20,32,Mexico City Grand Prix,2023-10-29,20:00:00,https://en.wikipedia.org/wiki/2023_Mexico_City...,2023-10-27,18:30:00,2023-10-27,22:00:00,2023-10-28,17:30:00,2023-10-28,21:00:00,\N,\N,1981-onward
1099,1118,2023,21,18,São Paulo Grand Prix,2023-11-05,17:00:00,https://en.wikipedia.org/wiki/2023_S%C3%A3o_Pa...,2023-11-03,14:30:00,2023-11-04,14:30:00,\N,\N,2023-11-03,18:00:00,2023-11-04,18:30:00,1981-onward
1100,1119,2023,22,80,Las Vegas Grand Prix,2023-11-19,06:00:00,https://en.wikipedia.org/wiki/2023_Las_Vegas_G...,2023-11-17,04:30:00,2023-11-17,08:00:00,2023-11-18,04:30:00,2023-11-18,08:00:00,\N,\N,1981-onward
1101,1120,2023,23,24,Abu Dhabi Grand Prix,2023-11-26,13:00:00,https://en.wikipedia.org/wiki/2023_Abu_Dhabi_G...,2023-11-24,09:30:00,2023-11-24,13:00:00,2023-11-25,10:30:00,2023-11-25,14:00:00,\N,\N,1981-onward

<font size = "5">

(d) Aggregate and sort

<font size = "3">

- Import the "data_raw/sprint_results.csv" file
- Obtain the maximum of "laps" by "driverId" <br> 
using ``` .groupby().agg() ```
- Sort the teams in descending order using of <br>
the maximum of laps using ``` .sort_values() ```

In [27]:
# Write your own code
sprint_results_2=pd.read_csv("data_raw/sprint_results.csv")

# aggregation
driveragg_2=(sprint_results.groupby('driverId').agg(
    maximum_laps=('laps','max')
))
driveragg_2

# sorting 
sorting_driveragg_2=driveragg_2.sort_values(by="maximum_laps",ascending=False)
sorting_driveragg_2

          maximum_laps
driverId
1                   24
4                   24
854                 24
853                 24
852                 24
849                 24
847                 24
846                 24
844                 24
842                 24
841                 24
840                 24
839                 24
832                 24
830                 24
825                 24
822                 24
817                 24
815                 24
20                  24
8                   24
855                 24
848                 23
9                   18

<font size = "5">

(e) Rename column

<font size = "3">

- Import the "data_raw/sprint_results.csv" file
- Rename the column "time" to "time_unformatted"

HINT: Create a dictionary and use ```.rename(columns = ...)``` <br>
See Lecture 15

In [30]:
# Write your own code

# rename column
sprint_results_3=pd.read_csv("data_raw/sprint_results.csv")
sprint_results_3.rename(columns={'time':'time_unformatted'})
sprint_results_3

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,fastestLapTime,statusId
0,1,1061,830,9,33,2,1,1,1,3,17,25:38.426,1538426,14,1:30.013,1
1,2,1061,1,131,44,1,2,2,2,2,17,+1.430,1539856,17,1:29.937,1
2,3,1061,822,131,77,3,3,3,3,1,17,+7.502,1545928,17,1:29.958,1
3,4,1061,844,6,16,4,4,4,4,0,17,+11.278,1549704,16,1:30.163,1
4,5,1061,846,1,4,6,5,5,5,0,17,+24.111,1562537,16,1:30.566,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,116,1095,840,117,18,15,16,16,16,0,24,+50.700,1862007,4,1:15.425,1
116,117,1095,839,214,31,6,17,17,17,0,24,+51.756,1863063,5,1:16.097,1
117,118,1095,4,214,14,7,18,18,18,0,24,+53.985,1865292,5,1:14.764,1
118,119,1095,849,3,6,16,19,19,19,0,24,+1:16.850,1888157,4,1:16.525,1
119,120,1095,848,3,23,11,\N,R,20,0,12,\N,\N,4,1:15.998,31

<font size = "5">

(f) Merge dataset

<font size = "3">

- Import the "data_raw/sprint_results.csv" and <br>
"data_raw/constructors.csv" files
- Create a new dataset with  ```pd.merge()``` using <br>
"sprint_results" as the primary dataset, and <br>
"constructors" as the secondary dataset, merging on <br>
the column "constructorId"
- To get full points **ONLY** merge the "nationality" column <br>
from the secondary dataset (not all the columns)

HINT: Use ```[[...]]``` to extract a subset of columns <br>
from the secondary dataset before merging, including the <br>
"constructorId" column

In [49]:
# Write your own code
sprint_results_4=pd.read_csv("data_raw/sprint_results.csv")
constructors_2=pd.read_csv("data_raw/constructors.csv")
constructors_2_nationality=constructors_2[["nationality","constructorId"]]

# pd.merge()
merge_dataset=pd.merge(sprint_results_4,constructors_2_nationality,on="constructorId",how="left") 
merge_dataset

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,fastestLapTime,statusId,nationality
0,1,1061,830,9,33,2,1,1,1,3,17,25:38.426,1538426,14,1:30.013,1,Austrian
1,2,1061,1,131,44,1,2,2,2,2,17,+1.430,1539856,17,1:29.937,1,German
2,3,1061,822,131,77,3,3,3,3,1,17,+7.502,1545928,17,1:29.958,1,German
3,4,1061,844,6,16,4,4,4,4,0,17,+11.278,1549704,16,1:30.163,1,Italian
4,5,1061,846,1,4,6,5,5,5,0,17,+24.111,1562537,16,1:30.566,1,British
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,116,1095,840,117,18,15,16,16,16,0,24,+50.700,1862007,4,1:15.425,1,British
116,117,1095,839,214,31,6,17,17,17,0,24,+51.756,1863063,5,1:16.097,1,French
117,118,1095,4,214,14,7,18,18,18,0,24,+53.985,1865292,5,1:14.764,1,French
118,119,1095,849,3,6,16,19,19,19,0,24,+1:16.850,1888157,4,1:16.525,1,British
119,120,1095,848,3,23,11,\N,R,20,0,12,\N,\N,4,1:15.998,31,British